"""Create new Table Users, Rooms, Bookings

Revision ID: 0e493aefdbe0
Revises: b8d7abaa45de
Create Date: 2023-10-09 13:54:14.801640

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0e493aefdbe0'
down_revision: Union[str, None] = 'b8d7abaa45de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
