"""Create new Table Users, Rooms, Bookings

Revision ID: be030b6742df
Revises: 0e493aefdbe0
Create Date: 2023-10-10 17:53:04.887635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be030b6742df'
down_revision: Union[str, None] = '0e493aefdbe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
